version: '3'
services:
  web:
    build: .
    ports:
      - '5000:80'
    expose:
      - 80
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost//api/v1/ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: tXfr4AVPzPhNTRVg
    expose:
      - 5432
